name:                krestia-haskell
version:             0.1.0.0
github:              "Sam647254/krestia-haskell"
license:             UNLICENSE
author:              "Sam Wang"
maintainer:          "info@5am.works"
copyright:           "2021 5AM WORKS"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/krestia-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- mtl
- split

library:
  source-dirs: src

executables:
  krestia-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - krestia-haskell

tests:
  krestia-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - krestia-haskell
    - hspec